repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11  # Remplacez par votre version de Python

  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        entry: python manage.py test
        language: system
        pass_filenames: false
