# Generated by Django 5.0.6 on 2024-07-10 14:08

from django.db import migrations
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Client = apps.get_model("comptes", "Client")
    for row in Client.objects.all():
        row.identifiant_unique = uuid.uuid4()
        row.save(update_fields=["identifiant_unique"])


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_client_adresse_client_date_creation_client_email_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
