# Generated by Django 5.0.6 on 2024-07-10 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0004_auto_20240710_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="identifiant_unique",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
