# Generated by Django 5.0.6 on 2024-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0005_client_prenom_alter_client_identifiant_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("fournisseur", "Fournisseur"), ("client", "Client")],
                default="fournisseur",
                max_length=20,
            ),
        ),
    ]
