# Generated by Django 5.0.6 on 2024-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("fournisseur", "Fournisseur"), ("client", "Client")],
                max_length=20,
                null=True,
            ),
        ),
    ]
