# Generated by Django 5.0.6 on 2024-07-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0007_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "fournisseur"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
