# Generated by Django 5.0.6 on 2024-07-13 18:06

from django.db import migrations


def assign_clients_to_first_fournisseur(apps, schema_editor):
    Client = apps.get_model("comptes", "Client")
    CustomUser = apps.get_model("comptes", "CustomUser")

    fournisseur = CustomUser.objects.filter(role="fournisseur").first()

    if fournisseur:
        # Assign all clients to the first fournisseur found
        Client.objects.filter(fournisseur__isnull=True).update(fournisseur=fournisseur)


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0008_client_fournisseur"),
    ]

    operations = [
        migrations.RunPython(assign_clients_to_first_fournisseur),
    ]
