# Generated by Django 5.0.6 on 2024-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0010_make_fournisseur_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="unite_versement",
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="solde",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
