# Generated by Django 5.0.6 on 2024-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0011_client_unite_versement_customuser_solde"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="platform_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
