# Generated by Django 5.0.6 on 2024-07-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0012_customuser_active_customuser_platform_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
                ),
            ],
        ),
    ]
