# Generated by Django 5.0.6 on 2024-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0013_globalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
