# Generated by Django 5.0.6 on 2024-07-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comptes", "0011_client_unite_versement_customuser_solde"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "montant_restant",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cases_cochees", models.PositiveIntegerField(default=0)),
                ("nombre_cases", models.PositiveIntegerField(default=31)),
                ("active", models.BooleanField(default=True)),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="comptes.client"
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        limit_choices_to={"role": "fournisseur"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
